# Seed-VC V2 baseline configuration

diffusion_steps: 30
length_adjust: 1.0

# Controls linguistic intelligibility
intelligibility_cfg_rate: 0.7

# Controls similarity to Yali reference
similarity_cfg_rate: 0.7

# AR sampling
top_p: 0.9
temperature: 1.0
repetition_penalty: 1.0

# IMPORTANT:
# true = convert accent/style/emotion
convert_style: true

# false = use Yali reference
anonymization_only: false